
export const initialVoiceId = [
  {voiceName: "Rachel", voiceId: "21m00Tcm4TlvDq8ikWAM"},
  {voiceName: "Clyde", voiceId: "2EiwWnXFnvU5JabPnv8n"},
  {voiceName: "Domi", voiceId: "AZnzlk1XvdvUeBnXmlld"},
  {voiceName: "Dave", voiceId: "CYw3kZ02Hs0563khs1Fj"},
  {voiceName: "Fin", voiceId: "D38z5RcWu1voky8WS1ja"},
  {voiceName: "Bella", voiceId: "EXAVITQu4vr4xnSDxMaL"},
  {voiceName: "Antoni", voiceId: "ErXwobaYiN019PkySvjV"},
  {voiceName: "Thomas", voiceId: "GBv7mTt0atIp3Br8iCZE"},
  {voiceName: "Charlie", voiceId: "IKne3meq5aSn9XLyUdCD"},
  {voiceName: "Emily", voiceId: "LcfcDJNUP1GQjkzn1xUU"},
  {voiceName: "Elli", voiceId: "MF3mGyEYCl7XYWbV9V6O"},
  {voiceName: "Callum", voiceId: "N2lVS1w4EtoT3dr4eOWO"},
  {voiceName: "Patrick", voiceId: "ODq5zmih8GrVes37Dizd"},
  {voiceName: "Harry ", voiceId: "SOYHLrjzK2X1ezoPC6cr"},
  {voiceName: "Liam", voiceId: "TX3LPaxmHKxFdv7VOQHJ"},
  {voiceName: "Dorothy", voiceId: "ThT5KcBeYPX3keUQqHPh"},
  {voiceName: "Josh", voiceId: "TxGEqnHWrfWFTfGW9XjX"},
  {voiceName: "Arnold", voiceId: "VR6AewLTigWG4xSOukaG"},
  {voiceName: "Charlotte", voiceId: "XB0fDUnXU5powFXDhCwa"},
  {voiceName: "Matilda ", voiceId: "XrExE9yKIg1WjnnlVkGX"},
  {voiceName: "Matthew", voiceId: "Yko7PKHZNXotIFUBG7I9"},
  {voiceName: "James", voiceId: "ZQe5CZNOzWyzPSCn5a3c"},
  {voiceName: "Joseph", voiceId: "Zlb1dXrM653N07WRdFW3"},
  {voiceName: "Jeremy", voiceId: "bVMeCyTHy58xNoL34h3p"},
  {voiceName: "Michael ", voiceId: "flq6f7yk4E4fJM5XTYuZ"},
  {voiceName: "Ethan", voiceId: "g5CIjZEefAph4nQFvHAz"},
  {voiceName: "Gigi", voiceId: "jBpfuIE2acCO8z3wKNLl"},
  {voiceName: "Freya", voiceId: "jsCqWAovK2LkecY7zXl4"},
  {voiceName: "Grace", voiceId: "oWAxZDx7w5VEj9dCyTzz"},
  {voiceName: "Daniel", voiceId: "onwK4e9ZLuTAKqWW03F9"},
  {voiceName: "Serena", voiceId: "pMsXgVXv3BLzUgSXRplE"},
  {voiceName: "Adam", voiceId: "pNInz6obpgDQGcFmaJgB"},
  {voiceName: "Nicole", voiceId: "piTKgcLEGmPE4e6mEKli"},
  {voiceName: "Jessie", voiceId: "t0jbNlBVZ17f02VDIeMI"},
  {voiceName: "Ryan ", voiceId: "wViXBPUzp2ZZixB1xQuM"},
  {voiceName: "Sam", voiceId: "yoZ06aMxZJJ28mfd3POQ"},
  {voiceName: "Glinda", voiceId: "z9fAnlkpzviPz146aGWa"},
  {voiceName: "Giovanni", voiceId: "zcAOhNBS3c14rBihAFp1"},
  {voiceName: "Mimi ", voiceId: "zrHiDhphv9ZnVXBqCLjz"},
  {voiceName: "Voice name", voiceId: "PKhGjpjGR0GgIIta4TDg"},
  {voiceName: "Gal testing ", voiceId: "g23ky68qrer954JVbNNG"},
]